cs/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, re_path
from csinterface import views
from accounts import views as accounts_views

urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^signup/$', accounts_views.signup, name = 'signup'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(), name = 'logout'),
    re_path(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name = 'login'),
    re_path(r'^price_bid/(?P<id>\d+)/$', views.price_bid, name='price_bid'),
    re_path(r'^company/(?P<pk>\d+)/$', views.company, name='company'),
    re_path(r'^company/(?P<pk>\d+)/new_bid/$', views.new_bid, name='new_bid'),
    re_path(r'^about/$', views.about, name='about'),
    re_path(r'^company/(?P<pk>\d+)/test/$', views.test, name='test'),
    path('admin/', admin.site.urls),

]

accounts/models.py
from django.db import models

# Create your models here.

csinterface/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.functions import Lower

class Company(models.Model):
    name = models.CharField(max_length=30, unique=True)
    address = models.CharField(max_length=200)
    # is_in_debt = models.BooleanField ("Is in debt ?",default=0, blank=True) TODO 

    class Meta:
        ordering = [Lower('name')]

    def __str__(self):
        return self.name

class Part(models.Model):
    number = models.CharField(max_length=20, default='None')
    description = models.CharField(max_length=100, default='None')
    location = models.CharField(max_length=10, default='None')
    count = models.CharField(max_length=10, default='None')
    price = models.CharField(max_length=10, default='None')
    type = models.CharField(max_length=10, default='None')
         
    def __str__(self):
        return self.number
    
class PriceBid(models.Model):
    class CustomerChoices(models.TextChoices):
        REGULAR = 'RG', 'Regular'
        DEALER = 'DL', 'Dealer'
        GROUP = 'GR', 'Tajmac Group'

    number = models.CharField("nabídka číslo", max_length=20, unique=True)
    parts = models.ManyToManyField(Part, related_name='parts')
    text = models.CharField(max_length=5000, blank=True)
    created_at = models.DateField(auto_now_add=True)
    customer_type = models.CharField(max_length=2, choices=CustomerChoices.choices, default='RG',)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='price_bid_counter', default='initial_company')

    class Meta:
        ordering = ['-created_at']
            # minusem pred 'created at' prohazuju poradi nejstarsi/ nejnovejsi

    def __str__(self):
        return self.number

class ServiceCase(models.Model):
    number = models.CharField(max_length=100)
    in_warranty = models.BooleanField
    description = models.CharField(max_length=1000)
    updated_by = models.ForeignKey(User, related_name='services', on_delete=models.CASCADE)
    company = models.ForeignKey(Company, related_name='services', on_delete=models.CASCADE)

class Test(models.Model):
    nazev = models.CharField(max_length=50, default='*')
    popis =models.CharField(max_length=50, default='*')
    sklad =models.CharField(max_length=50, default='*')
    pocet =models.CharField(max_length=50, default='*')
    cena =models.CharField(max_length=50, default='*')
    typ =models.CharField(max_length=50, default='*')

    def __str__(self):
        return self.nazev

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

csinterface/forms.py
from django import forms
from .models import PriceBid
from django.urls import reverse_lazy
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from crispy_forms.bootstrap import InlineRadios #todo try to format inlne / how ?



class NewPriceBidForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'Uložit'))
       
    text = forms.CharField(widget=forms.Textarea(attrs={'rows': 5, 'placeholder': 'Text k řádkům nabídky'}))
    customer_type = forms.ChoiceField(choices=PriceBid.CustomerChoices.choices, widget=forms.RadioSelect, initial='RG')
    class Meta:
        model = PriceBid
        fields = ('number', 'parts', 'text', 'customer_type', 'company')

accounts/views.py
from django.contrib.auth import login as auth_login
from django.shortcuts import render, redirect
from .forms import SignUpForm


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid:
            user = form.save()
            auth_login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form':form})

csinterface/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from .models import Company, PriceBid, Part
from .forms import NewPriceBidForm


def home(request):
    companies = Company.objects.all()
    bids = PriceBid.objects.all()
    
    for company in companies:
        bid_count = PriceBid.objects.all()
    context = {'companies':companies, 'bids':bids,'bid_count': bid_count, 'company': company}
    return render(request, 'home.html', context)

def company(request, pk):
    company = get_object_or_404(Company, pk=pk)
    bids = PriceBid.objects.all()
    context = {'company':company, 'bids':bids}
    return render(request, 'company.html', context)

def about(request):
    # user = user.objects.first() #TODO: vezme aktualne prihlaseneho uzivatele
    
    if request.method == 'POST':
        form = NewPriceBidForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = NewPriceBidForm()
    context = {'form':form}
    return render (request, 'about.html', context)
    
    

def price_bid(request, id):
    price_bid = get_object_or_404(PriceBid, id=id)
    parts_list = price_bid.parts.all()
    return render(request, 'price_bid.html', {'price_bid':price_bid, 'parts_list':parts_list,})
    
def new_bid(request, pk):
    company = get_object_or_404(Company, pk=pk)
    initial_company = company.pk

    if request.method == 'POST':
        form = NewPriceBidForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
        
    else:
        form = NewPriceBidForm(initial={'company': initial_company})
        
    context = {'company':company,'form':form}
    return render (request, 'new_bid.html', context)

def test(request, pk):
    company = get_object_or_404(Company, pk=pk)

    if request.method == 'POST':
        form = NewPriceBidForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = NewPriceBidForm()
        
    context = {'company':company,'form':form}
    return render (request, 'test.html', context)

templates/about.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
About
{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"> <a href="/">Home</a> </li>
<li class="breadcrumb-item active">About</li>
{% endblock %}

{% block content%}
<body>
      
    <br>
    <h6>Body ktere je treba udelat:</h6>
    <h6>- pohlidat aby pri vymazani cenove nabidky nezmizely dily z databaze</h6>
    <h6>- 👌 pri tvorbe nabidky si prevzit spolecnost, abych ji nemusel vybirat</h6>
    <h6>- pri vyberu dilu z databaze vybrat vsechny jeho instance</h6>
    <h6>- implementovat moznost upravy cenove nabidky (odmazani radku, uprava textu atd)</h6>
    <h6>- 👌 zprovoznit nejakou formu rendrovani formularu (crispy / widget tweaks)</h6>
    <h6>- po vyplneni formulare provest redirect na nove vznikly price bid</h6>
    <h6>- pridat moznost vkladat servsini pripady</h6>
    <h6>- predelat semafor na servisni pripady</h6>
    <h6>- {{company.pk}}</h6>
    <h6></h6>
    <form method="post">
        <button type="submit" class="btn btn-success">HIT</button>
        {% csrf_token %}
        {% crispy form %}
    </form>
  
    <br>
    <br>
    <div class="card-footer fixed-bottom">autor: Jaromír Kaláb</div>
    
    
</body>
{% endblock %}

templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %} Manurhin Customer Service {% endblock %}</title>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    {% block stylesheet%} {% endblock %}
</head>
<body>
    {% block body %}
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Customer Support</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mainMenu">
          {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ user.username }}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                  <a class="dropdown-item" href="#">My account</a>
                  <a class="dropdown-item" href="#">Change password</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                </div>
              </li>
            </ul>
          {% else %}
            <form class="form-inline ml-auto">
              <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
              <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
            </form>
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="container">
        <ol class="breadcrumb my-4">
            {% block breadcrumb %}

            {% endblock %}

        </ol>
    {% block content %}

    {% endblock %}
    </div>

    {% block scripts %}
    
    {% endblock %}
    
    {% endblock body%}
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/company.html
{% extends 'base.html' %}
{% load static %}


<body>
  {% block breadcrumb %}
  
    <li class="breadcrumb-item"> <a href="/">Home</a> </li>
    <li class="breadcrumb-item"> <a href="{% url 'company' company.pk %}">{{company.name}}</a></li>

  {% endblock %}
  
  {% block content%}
    
    <div class="container mb-4">
      <a href="{% url 'new_bid' company.pk %}" class="btn btn-primary">Vytvořit nabídku</a>
    </div>

  <div class="container">
    <table class="table">
      <thead class="thead-inverse">
        <tr>
          <th>Cenová nabídka</th>
          <th>Servisní případ</th>
        </tr>
      </thead>
      <tbody>
        {% for bid in bids %}
          {% if bid.company_id == company.id %}
            <tr>
              <td>
                <a href="{% url 'price_bid' bid.id %}">{{bid.number}}</a>
              </td>
              <td>*</td>
            </tr> 
          {% endif %}
        {% endfor %}
        <p> PK spolecnosti je: {{company.pk}}</p>
      </tbody>
    </table>
  </div>
  
</body>
{% endblock%}
</html>

templates/home.html
{% extends 'base.html' %}

{% block breadcrumb %}
    <li class="breadcrumb-item active">
        <a href="/">Home</a>
    </li>
{% endblock %}

{% block content%}


<div class="container mb-4">
    <button type="button" class="btn btn-warning"><a href="/admin">ADMIN</a></button>
    <a href="#" class="btn btn-primary">Vytvořit nabídku</a>
    <a href="#" class="btn btn-primary">Založit servisní případ</a>
  </div>

<table class="table table-striped">
    <thead class="thead-inverse">
        <tr>
            <th>Společnost</th>
            <th>Nabídek celkem</th>
            <th>Servisů celkem</th>
            <th>Naposledy upraveno</th>
        </tr>
    </thead>
    <tbody>
        {% for company in companies %}
        <tr>
            <td>
                <a href="{% url 'company' company.pk %}">{{company.name}}</a>
                 <br>
                <small class="text-muted d-block">{{company.address}}</small>
            </td>
            <td class="text-left">{{company.price_bid_counter.all.count}}
                <small class="text-muted d-block">poslední: {{company.price_bid_counter.last}}</small>
            </td>
            <td class="text-center"></td>
            <td class="text-center">{{company.bids.created_at.last}}</td>    
        </tr>
        {% endfor %}
        
    </tbody>
</table>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'home' %}">Customer Support</a>
    </h1>
    <div class="row justify-content-center">
      <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">Log in</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {{ form.as_div }}
              <button type="submit" class="btn btn-primary btn-block">Log in</button>
            </form>
          </div>
          <div class="card-footer text-muted text-center">
            Nový v týmu Manurhinu? <a href="{% url 'signup' %}">Sign up</a>
          </div>
        </div>
        <div class="text-center py-2">
          <small>
            <a href="#" class="text-muted">Zapomněl jsi heslo?</a>
          </small>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/new_bid.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block breadcrumb %}
<li class="breadcrumb-item"> <a href="/">Home</a> </li>
<li class="breadcrumb-item"> <a href="{% url 'company' company.pk %}">{{company.name}}</a></li>
<li class="breadcrumb-item active"> Nová cenová nabídka </li>
{% endblock %}

{% block content %}
    
        {% csrf_token %}
        {% crispy form %}
       
    
{% endblock %}

{% block scripts %}
    <script>    
        $("#id_parts").select2();
    </script>    
{% endblock %}

templates/price_bid.html
{% extends 'base.html' %}

{% block breadcrumb %}
    <li class="breadcrumb-item"> <a href="/">Home</a> </li>
    <li class="breadcrumb-item"> <a href="{% url 'company' price_bid.company.pk %}">{{price_bid.company}}</a></li>
    <li class="breadcrumb-item active"> {{price_bid.number}} </li>
    
{% endblock %}
{%block content %}
    <div class="container">
        <table class="table">
            <h6>nabídka č. {{price_bid.number}} <small class="text-muted d-block">{{price_bid.created_at}}</small></h6>
            <thead class="thead-inverse">
                <tr>
                    <th>znak</th>
                    <th>popis</th>
                    <th>cena (VN)</th>
                    <th>dostupnost</th>
                </tr>
            </thead>
            <tbody class="tbody">
                {% for part in parts_list%}
                <tr>
                    
                    <td>{{part.number}}</td>
                    <td>{{part.description}}</td>
                    <td>{{part.price}} CZK/ks</td>
                    <td>{{part.location}}</td>
                    <td>{{part.count}}x</td>
                    <td>{{price}}</td>
                </tr>
                {% endfor %}
            </tbody>
            <br>
        </table>
        <textarea name="" id="" cols="30" rows="10">{{price_bid.text}}</textarea>
    </div>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}


{% block body %}
    <div class="container">
    <h2>Sign up</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_div }}
        <button type="submit" class="btn btn-primary">Create an account</button>
    </form>
    </div>
{% endblock %}

templates/test.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {% crispy form %}
        <button type="submit" class="btn">hit</button>
    </form>
{% endblock %}